# Generated by Django 5.2.5 on 2025-09-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artoon2d_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured_image',
            new_name='image',
        ),
    ]
